# Generated by Django 3.2 on 2021-04-21 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210419_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210421_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_quantity',
            new_name='PurchaseQuantity',
        ),
    ]
