# Generated by Django 3.2 on 2021-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210419_1401'),
        ('users', '0005_rename_follow_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasequantity',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasequantity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='purchasequantity',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='purchasequantity',
            name='quantity',
        ),
    ]
