# Generated by Django 3.2 on 2021-04-28 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20210419_1401'),
        ('users', '0006_auto_20210428_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseQuantity',
            new_name='PurchaseList',
        ),
    ]
