# Generated by Django 3.2 on 2021-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210419_1401'),
        ('users', '0007_rename_purchasequantity_purchaselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='recipes',
            field=models.ManyToManyField(related_name='in_purchase_list', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
