# Generated by Django 3.2 on 2021-04-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_purchaselist_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselist',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
