# Generated by Django 3.2 on 2021-04-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210419_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_rename_recipes_purchaselist_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_purchase_list', to='recipes.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseList',
        ),
    ]
