# Generated by Django 3.2 on 2021-04-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_quantity',
            new_name='IngredientRecipe',
        ),
    ]
