# Generated by Django 3.1.7 on 2021-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210305_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
