# Generated by Django 3.2 on 2021-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210414_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('title',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='green', max_length=50, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='test', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
