# Generated by Django 3.1.7 on 2021-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210305_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(verbose_name='Время приготовления, мин'),
        ),
    ]
