# Generated by Django 3.2 on 2021-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210501_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientrecipe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='IngredientRecipe'),
        ),
    ]
