# Generated by Django 3.1.7 on 2021-03-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210306_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/media/recipe/uploads/', verbose_name='Картинка'),
        ),
    ]
